<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Nouvelle Categorie </title>
</head>
<body>
    
    <h1>Ajout Categorie</h1>
    
    <div class="container">

    <form action="<?=$_SERVER['PHP_SELF']?> " method="POST">
    <div>
    <h3><a href="listeCat.php">Home</a></h3>
    </div>


    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nom </label>
    <div class="col-sm-2"  name="nom">                
    
    <input type="text" name="nom" placeholder="Entez nom Categorie" >
    </div>
    </div>

    <div class="form-group row">
    <label  class="col-sm-2 col-form-label"> Description produit</label>
    <div class="col-sm-2"  name="description">                
    <textarea id="desp" placeholder="ecrivez quelque chose ici" name="description"></textarea>
    </div>
    </div>

    <div class="form-group row">
    <label  class="col-sm-2 col-form-labe" >Image du Categorie </label>
    <div class="col-sm-2"  name="image">                
    <input name="file" type="file" name="image" >
    </div>
    </div>


    <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
    <input type="submit" class="btn btn-primary" value="ADD">
    <input type="reset"  class="btn btn-danger" value="Reset">
    </div>
    </div>
    </form>
    </div>
</body>
</html>