<!DOCTYPE html>
<html lang="en">
<head>
<meta content="width=device-width, initial-scale=1" name="viewport" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

        body
        {
            font-family:'Poppins',sans-serif;
            background:linear-gradient(to right ,#cbb4d4,#20002c);
            position:center;
        }
        h1{
        color:white;
        text-transform:uppercase;
        } 
        .default:hover {
            background: #ff9800;
            color: white;
        }
        input[type="checkbox"] {
		transform:scale(1.5, 1.5);
    }

    </style>

    <title>Nouvelle Categorie </title>
</head>
<body>
<?php require_once("menu.php") ?>

    <h1>Ajout Categorie</h1>
    
    <div class="container">

    <form action="<?=$_SERVER['PHP_SELF']?> " method="POST">
   

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nom </label>
    <div class="col-sm-2"  name="nom">                
    
    <input type="text" name="nom" placeholder="Entez nom Categorie" >
    </div>
    </div>

    <div class="form-group row">
    <label  class="col-sm-2 col-form-label"> Description produit</label>
    <div class="col-sm-2"  name="description">                
    <textarea id="desp" placeholder="ecrivez quelque chose ici" name="description"></textarea>
    </div>
    </div>

    

    <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
    <input type="submit" class="btn btn-primary" value="Ajouter">
    <input type="reset"  class="btn btn-danger" value="Annuler">
    </div>
    </div>
    </form>
    </div>
</body>
</html>