<!Doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
<h1>Listes des Produits </h1>
          
        
<div class="container">
<form action="editerProd.php?id=<?php echo $id?>" method="POST">

    <div>
    <h3><a href="ListeProduit.php">Home</a>
    </h3>
    </div>

    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nom </label>
    <div class="col-sm-2"  name="nom">                

    <input type="text" name="nom" placeholder="Entez nom Produit" value="<?php echo !empty($nom)?$nom:''?>" id="nom" >
    </div>
    </div>

    <div class="form-group row">
    <label  class="col-sm-2 col-form-label"> Description produit</label>
    <div class="col-sm-2"  name="description">                
    <textarea  placeholder="ecrivez quelque chose ici" name="description" value="<?php echo !empty($description)?$description:'' ?>"></textarea>
    </div>
    </div>

    <div class="form-group row">
    <label  class="col-sm-2 col-form-label"> Prix produit</label>
    <div class="col-sm-2"  name="prix">  
    <input type="text" name="prix" placeholder="Entez prix Produit" value="<?php echo !empty($prix)?$prix:''?>" id="prix" >

    </div>
    </div>

    <div class="form-group row">
                <label  class="col-sm-2 col-form-label">Categorie</label>
                <div class="col-sm-2"  name="categorie">                

                <select name="categorie">
                    <?php foreach ($categories as $categorie): ?>
                    <option value="<?=$categorie['id'] ?>"><?=$categorie['nom'] ?></option>
                    <?php endforeach ; ?>
                </select>
                
                </div>
                </div>
                


    <div class="form-group row">
         <div class="offset-sm-2 col-sm-10">
         <button type="submit" class="btn btn-success" name="editer"><i class="fa fa-save" ></i> Edit</button>

        </div>
    </div>
</form>
</div>

      
</body>
</html>
