<!Doctype html>
<html>
<head>
<meta content="width=device-width, initial-scale=1" name="viewport" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script> 
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>   
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
   
    <style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

        body
        {
            font-family:'Poppins',sans-serif;
            background:linear-gradient(to right ,#cbb4d4,#20002c);
            position:center;
        }
        h1{
        color:white;
        text-transform:uppercase;
        } 
        .default:hover {
            background: #ff9800;
            color: white;
        }
        input[type="checkbox"] {
		transform:scale(1.5, 1.5);
    }

    </style>

</head>
<body>
<?php require_once("menu.php") ?>

<h1>Listes des Categories </h1>
 <table class="table table-striped table-hover table-bordered " id="cat" >
      <thead class="bg-dark text-white">
        
      <th scope="col" > id Categorie </th> 
      <th scope="col">Nom Categorie </th>
      <th scope="col">Description</th>
      <th scope="col">Suppression</th>
      <th scope="col">Modification</th>
      </thead>
      <tbody>

          <?php foreach ($categories as $categorie):?>
          <tr>
              <td scope="row">
                  <?= $categorie['id']?>
              </td>
              <td scope="row">
                  <?= $categorie['nom']?>
              </td>
              <td scope="row">
                  <?= $categorie['description']?>
              </td scope="row">
              <td><button type="button" class="btn-danger btn"><a onclick="return confirm('Are you sure you want to delete this')"  href="deleteCat.php?id=<?=$categorie['id']?>" class="text-white">Supprimer</a> </button></td>
              <td><button type="button" class="btn-primary btn"><a href="editCat.php?id=<?php echo $categorie['id'];?>" class="text-white">Editer</a> </button>
             
              </td>
              

          
          </tr>
          <?php endforeach; ?>
      </tbody>
  </table>
<script>

$(document).ready(function() {
    $('#cat').DataTable();
} );

</script>

</body>
</html>
