<!Doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

        body
        {
            font-family:'Poppins',sans-serif;
            background:linear-gradient(to right ,#cbb4d4,#20002c);
            position:center;
        }
        h1{
        color:white;
        text-transform:uppercase;
        } 
    

    </style>
</head>
<body>
<?php require_once("menu.php") ?>

<?php 
    if (isset($_SESSION['message'])): ?>
        <div class="alert alert-<?=$_SESSION['msg'] ?>"> 
        <?php
            echo'<div class=alert alert-success>'.$_SESSION['message'].'</div>';
            unset ($_SESSION['message']);
        ?>


    </div>
    <?php endif ?>    

   <h1>Liste des Produits </h1>
    <br>
   <table class="table table-striped table-hover table-bordered" >
        <thead class="bg-dark text-white">
        
        <th scope="col">cochez</th>
        
        <th scope="col"> Reference Produit </th> 
        <th scope="col">Nom Produit </th>
        <th scope="col">description</th>
        <th scope="col">Prix </th>
        <th scope="col">Categories</th>
        <th scope="col">Image</th>
        <th scope="col"></th>
        <th scope="col"></th>
        
        </thead>
        <tbody>
        

            <?php foreach ($produits as $produit):?>
            <tr>
            <td scopte="row"> <input type="checkbox" name="deleteMulti[]">
            </td>
                <td scope="row">
                    <?= $produit['id']?>
                </td>
                <td scope="row">
                    <?= $produit['nom']?>
                </td>
                <td scope="row">
                    <?= $produit['description']?>
                </td scope="row">
                
                <td scope="row">
                    <?= $produit['prix']?>
                </td>
                
                <td scope="row">
                    <?= $produit['nom_categorie']?>
                </td>
                
                
                </td scope="row">
              
               
                <td scope="row">
                    <?php  echo '<img src="upload/'.$produit['image'].'"width="100px;" height="100px; alt="image">';?>
            
                </td>
                </td scope="row">
                
                </td scope="row">
                </td scope="row">
                
                
              <td><button type="button" class="btn-danger btn"><a onclick="return confirm('Are you sure you want to delete this')"  href="delete.php?id=<?=$produit['id']?>" class="text-white">Supprimer</a> </button></td>
              
              <td><button type="button" class="btn-primary btn"><a href="editerProd.php?id=<?php echo $produit['id'];?>" class="text-white">Editer</a> </button>
             
              </td>
              


            </tr>
            <?php endforeach; ?>

            </tbody>

    </table>

    <div>
    </div>

            
              

</body>
</html>
