<!Doctype html>
<html>
<head>
<meta charset="utf-8"> 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

    <form action="<?=$_SERVER['PHP_SELF']?>" method="post" >
    <div class="form-group">
        <label class=" col-sm-2 col-form-label">Login</label>
        <div class="col-sm-2">
        <input type="text" name="login" class="form-control form-control-lg">
        </div>
        </div>

        

        <div class="form-group">
        
        <label class=" col-sm-2 col-form-label">PASSWORD</label>
        <div class="col-sm-2">
        <input type="password" name="pwd" class="form-control form-control-lg">
        </div>
        </div> 

        <div class=" col-sm-10 col-form" >        
        <input type="submit" value="Connexion" class="btn btn-primary">
        </div>

    </form>

</body>
</html>